# These keys are found in your SonarCloud dashboard 'Information' tab
sonar.projectKey=ndrlannazriel_Project-Sentinel
sonar.organization=ndrlannazriel

# This tells SonarCloud where your actual code is
sonar.sources=src
sonar.host.url=https://sonarcloud.io

# Since this is a JavaScript project
sonar.javascript.lcov.reportPaths=coverage/lcov.info